### ISSUE TITLE
New quick keys

### ISSUE THREAD

**Issue by dsakura** [Syrious/foundryvtt-quick-keys#1]
Hello, congrats and thank you!
So, if I want to add a new quick key, for some subtool, like draw a circle, I need to edit the keybindings.js, right? And its possible to add subtools? Thanks again

**Comment by Syrious** [comment]
Hi there,

to add a key for one of the default tabs you just need to assign a key in "Configure Controls".

Currently, sub tabs are not supported, but I'll look into it. 

<img width="932" alt="image" src="https://github.com/user-attachments/assets/f3cbda13-0d73-4407-8506-7eeaf7e1e2ca">

**Comment by dsakura** [comment]
Alright, It will be great! Thanks!
